version: "3.2"
services:
  parity:
    image: mcd-test
    container_name: parity
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8545"
      - "8546"
    user: root
    working_dir: /home/parity
    command: ["--chain=/home/parity/config/parity-dev-constantinopole.json",
              "--tracing=on",
              "--pruning=archive",
              "--jsonrpc-interface=all",
              "--jsonrpc-hosts=all",
              "--base-path=/home/parity/.local/share/io.parity.ethereum/"]

  testchain-dss-deployer:
    build:
      context: dapphub-tools
    image: makerdao/dapphub-tools
    container_name: testchain-dss-deployer
    privileged: true
    working_dir: /home/maker
    volumes:
      - $PWD/config/parity/keys:/testchain-data/keys
      - $PWD/bin/deploy-mcd.sh:/home/maker/deploy-mcd.sh
      - $PWD/src:/home/maker/src
    command: >
      /home/maker/deploy-mcd.sh

  pymaker-unit-testing-dss-deployer:
    build:
      context: dapphub-tools
    image: makerdao/dapphub-tools
    container_name: pymaker-unit-testing-dss-deployer
    privileged: true
    working_dir: /home/maker
    volumes:
      - $PWD/config/parity/keys:/testchain-data/keys
      - $PWD/bin/deploy-mcd.sh:/home/maker/deploy-mcd.sh
      - $PWD/src:/home/maker/src
      - $PWD/config/deploy-testchain_pymaker-unit-testing.json:/home/maker/src/deployment-scripts/deploy-testchain.json
    command: >
      /home/maker/deploy-mcd.sh

  auction-keeper-integration-testing-dss-deployer:
    build:
      context: dapphub-tools
    image: makerdao/dapphub-tools
    container_name: auction-keeper-integration-testing-dss-deployer
    privileged: true
    working_dir: /home/maker
    volumes:
      - $PWD/config/parity/keys:/testchain-data/keys
      - $PWD/bin/deploy-mcd.sh:/home/maker/deploy-mcd.sh
      - $PWD/src:/home/maker/src
      - $PWD/config/deploy-testchain_auction-keeper-integration-testing.json:/home/maker/src/deployment-scripts/deploy-testchain.json
    command: >
      /home/maker/deploy-mcd.sh

